### ISSUE TITLE
Seems to constantly hit the AWS api?

### ISSUE THREAD

**Issue by paul-civitas** [jonmosco/kube-ps1#152]
My shell seemed kinda sluggish, and I noticed in our organization's cloudtrail that I'm apparently constantly calling assume role.

It seems that kubeps1 when using AWS is constantly calling assume role somehow?

**Comment by jonmosco** [comment]
kube-ps1 only reads the kubectl config file (including the env variable KUBECONFIG), it does not call out to the AWS api.

**Comment by harrise-flwls** [comment]
@jonmosco I believe Paul is correct, although it's a little roundabout:

Many users of aws/eks generate their kubeconfig with `aws eks update-kubeconfig`, which yields configuration like the following ([docs](https://docs.aws.amazon.com/cli/latest/reference/eks/update-kubeconfig.html))

```
exec:
    apiVersion: client.authentication.k8s.io/v1beta1
    args:
    - --region
    - us-east-2
    - eks
    - get-token
    - --cluster-name
    - my-eks-cluster
    - --output
    - json
    - --role
    - arn:aws:iam::111122223333:role/eksctl-EKS-Linux-Cluster-v1-24-cluster-ServiceRole-j1k7AfTIQtnM
    command: aws
```

And kube-ps1 fetches context info by running `$KUBE_PS1_BINARY config current-context 2>/dev/null`. 

And `kubectl config current-context` seems to invoke the configured exec command (why? isn't everything it needs already available locally, in the config file?). This adds API calls and (for me) about 3s latency [edit: to a new shell and I think also when context was switched]

Shows in strace as:
```
execve("/usr/local/bin/aws", ["aws", "--region", "us-west-2", "eks", "get-token", "--cluster-name", "CLUSTER_NAME", "--output", "json"], [...] = 0 <0.000481>
```

A crude fix for me is to define:

```
# in .local/bin/kubectl-ps1
exec kubectl --user none "$@"
```
and set `KUBE_PS1_BINARY=kubectl-ps1`
